server:
  servlet:
    session:
      cookie:
        secure: true       # т.к. github.io всегда https
        same-site: none    # иначе браузер заблокирует куку

spring:
  application:
    name: habitus
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: habitus_user
    password: habitus_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000 # 3 секунды
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: WARN
        web.filter.CommonsRequestLoggingFilter: DEBUG

springdoc:
  swagger-ui:
#    disable-swagger-default-url: true
    operationsSorter: method     # или alpha, method, none
    tagsSorter: alpha            # или alpha, none
